# Generated by Django 3.2.10 on 2021-12-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile/')),
                ('full_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('cv', models.FileField(upload_to='profile/cv')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
